services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  seguroapi:
    build:
      context: .
      # dockerfile: OpenGovTech.Web.Dockerfile    
    ports:
      - "8080:8080" 
    container_name: seguroapi
  