services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"    

  seguroapi:
    build:
      context: ./desafio-seguro-api
    ports:
      - "8080:8080" 
    container_name: seguroapi
  